import type { Metadata } from 'next'
import { Commissioner } from 'next/font/google'
import './globals.css'

const commissioner = Commissioner({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${commissioner.className} text-black-100`}>{children}</body>
    </html>
  )
}
